### ISSUE TITLE
Adding player IDs from nflscrapR, nflfastR, and Pro Football Focus

### ISSUE THREAD

**Issue by TheMathNinja** [dynastyprocess/data#15]
I'm loving the map of player IDs in the mfl_players() function. Wondering if a few ID columns could get added/mapped:

nflscrapR / (I think this is old NFL API). Example: Kyle Orton = 00-0023541
nflfastR / (new NFL API). Example: Kirk Cousins = 32013030-2d30-3032-3936-303492e9d55e

You can find their code easily on GitHub

**Comment by TheMathNinja** [comment]
Also, Pro Football Reference and Pro Football Focus IDs would be extremely helpful. I know you can check out a map of these here:

https://github.com/leesharpe/nfldata/blob/master/data/pff_pfr_map_v1.csv

**Comment by tanho63** [comment]
Probably won't hit it from the actual code, but coming at it from here should be okay:

https://github.com/guga31bb/nflfastR-data/tree/master/roster-data

**Comment by tanho63** [comment]
PFR I've worked loosely on in the past, and mapping those to PFF is an interesting idea too.

**Comment by TheMathNinja** [comment]
I know nflfastR still doesn't have position designations native in their package due to new IDs. This could help out their work big time too.

**Comment by tanho63** [comment]
That's an interesting idea. Possibly more helpful in historical terms than it is for going forward

**Comment by trojanguard25** [comment]
I **think** I've mapped the vast majority of gsis_ids and pbp_ids in nflfastR 2020 play-by-play data to mfl_ids. I'd like to expand missing_ids.csv to have columns for gsis_ids and pbp_ids. Does that seem like the right thing to do so those ids can get populated into dbplayerids.csv?

**Comment by tanho63** [comment]
> I **think** I've mapped the vast majority of gsis_ids and pbp_ids in nflfastR 2020 play-by-play data to mfl_ids. I'd like to expand missing_ids.csv to have columns for gsis_ids and pbp_ids. Does that seem like the right thing to do so those ids can get populated into dbplayerids.csv?

@trojanguard25 that would be helpful! If you have a PR for these I can take a look at the integration
