### ISSUE TITLE
[Data Bug] Players missing from the mapping

### ISSUE THREAD

**Issue by Electronickss** [dynastyprocess/data#17]
**Describe the data bug**
Several players are not joined in the ID mapping file

** Which file is having trouble?**
https://github.com/dynastyprocess/data/blob/master/files/db_playerids.csv

**Expected data**
What should this look like?

player | pos | team | age | draft_year
-- | -- | -- | -- | --
Saquon Barkley | RB | NYG | NA | NA
Courtland Sutton | WR | DEN | NA | NA
Dak Prescott | QB | DAL | NA | NA
Blake Jarwin | TE | DAL | NA | NA
O.J. Howard | TE | TBB | NA | NA
Tarik Cohen | RB | CHI | NA | NA
Tyrell Williams | WR | LVR | NA | NA
JJ Arcega-Whiteside | WR | PHI | NA | NA
Marlon Mack | RB | IND | NA | NA
Adam Trautman | TE | NOS | NA | NA
Cole Kmet | TE | CHI | NA | NA
James Proche | WR | BAL | NA | NA
Jalen Hurts | QB | PHI | NA | NA
Albert Okwuegbunam | TE | DEN | NA | NA
Jordan Love | QB | GBP | NA | NA
Damien Williams | RB | KCC | NA | NA
Harrison Bryant | TE | CLE | NA | NA

**Comment by Electronickss** [comment]
https://i.imgur.com/72BwIxd.png

**Comment by tanho63** [comment]
Resolved in latest commit 0e7df9d
