### ISSUE TITLE
[Data Bug] FantasyPros mixing in old rankings

### ISSUE THREAD

**Issue by Electronickss** [dynastyprocess/data#18]
**Describe the data bug**
The default view of FantasyPros dynasty rankings mixes in some really old rankings (from this summer or farther), "take locking" value

**Which file is having trouble?**
Player-Values.csv

**Expected data**
Taylor and CEH were booted from top 15 dynasty assets as an example. Michael Gallup is now worth overall double what he was two days ago etc

**Comment by tanho63** [comment]
😡

-
Tan Ho
________________________________

**Comment by tanho63** [comment]
Resolved - thank you for reporting!
