### ISSUE TITLE
How are you supposed to read the player's value chart?

### ISSUE THREAD

**Issue by kypul** [dynastyprocess/data#19]
I know this isn't necessarily a data request but I just wanted to know how I'm supposed to read the chart and understand each player's value for a dynasty league in 2021. Thanks in advance!

**Comment by tanho63** [comment]
Hi! What chart are you referring to?

**Comment by tanho63** [comment]
@kypul

**Comment by kypul** [comment]
Like the values-picks.csv and values-players.csv. I want to make trades in my dynasty league but I'm not sure which column I'm supposed to check to make sure I'm getting equal or better value back.

**Comment by tanho63** [comment]
You can use the trade calculator app https://apps.dynastyprocess.com/calculator to help more directly with trades. 

Essentially, it's driven from the values in value_1qb and value_2qb, the sum of value for one side of a trade should be equal to the other side

**Comment by kypul** [comment]
Ohhhh ok, now I understand how the chart works! Thanks for all your work!
