### ISSUE TITLE
[Data Bug]

### ISSUE THREAD

**Issue by damj97** [dynastyprocess/data#21]
I found a duplicate gsis_id

Both MFL ids 11724 & 14683 gave a gsis_id of 00-0034641

I think gsis_id of 00-0034641 goes with MFL ID 14683 (Chris Jones)

**Comment by trojanguard25** [comment]
> I think gsis_id of 00-0034641 goes with MFL ID 14683 (Chris Jones)

This matches what is in nflfastr-roster.

mfld_id 11724 (Christian Jones) should have a gsis_id of 00-0031130 (according to nflfastr-roster).

**Comment by tanho63** [comment]
I'm planning a bit of a revamp of this in conjunction with tweaking @trojanguard25's PR #20 - I was previously sourcing gsis_id primarily from the Sleeper API - but with the new nflfastr-roster data repo (new since I wrote code) I can join on the sportradar ID and make sure the gsis-id comes from there instead - that should be more robust

**Comment by damj97** [comment]
Great guys, thanks.
One thing I've noticed about Sleeper is that their database isn't very clean. I found a bunch of bad IDs which I sent to them. I'm not sure what sites I'll scrape from, so right now I'm just making sure I have as many cross references as possible.
    On Monday, March 8, 2021, 11:20:08 AM EST, Tan Ho <notifications@github.com> wrote:  
 
 


I'm planning a bit of a revamp of this in conjunction with tweaking @trojanguard25's PR #20 - I was previously sourcing gsis_id primarily from the Sleeper API - but with the new nflfastr-roster data repo (new since I wrote code) I can join on the sportradar ID and make sure the gsis-id comes from there instead - that should be more robust

**Comment by tanho63** [comment]
That problem's cropped up before, I solved it like this: https://github.com/dynastyprocess/data/issues/13

**Comment by damj97** [comment]
Thanks, I'll check it out.
I started using Excel Power Queries in 2019 which is where I first learned about you guys.  I didn't plan last year ... so I look forward to learning more about scraping from you guys and FF data management.
    On Monday, March 8, 2021, 11:31:57 AM EST, Tan Ho <notifications@github.com> wrote:  
 
 


That problem's cropped up before, I solved it like this: #13

**Comment by tanho63** [comment]
Hiya! Sorry to leave this languishing for a bit - it should be solved as of the most recent commit. Closing.
