### ISSUE TITLE
[Data Request/Offer Of Help] 2021 Rookies

### ISSUE THREAD

**Issue by danabrey** [dynastyprocess/data#22]
Lots of missing IDs for 2021 rookies on db_playerids.csv - I'll happily try to gather some together this coming weekend unless you have it in the pipeline?

**Comment by tanho63** [comment]
Been dabbling with data pipeline work for quite a while - should have an update in the near-ish future!

**Comment by tanho63** [comment]
Hiya! Just finished up some automated tooling as of most recent commit that should clean up the 2021 rookies significantly, please give it a spin!

**Comment by danabrey** [comment]
Awesome! Working great, thanks.

One question just to reassure me - the players.csv used to have `age` as a property, right? I've switched to taking age directly from MFL now, but I just want to make sure I'm not going mad :)

**Comment by danabrey** [comment]
Just one funky issue so far (you know you love those). I've had a few emails from Terrace Marshall truthers asking me why I'm declaring him a bust already. While my temptation was to double down on that accidental conclusion...

Terrace Marshall's fantasypros_id in players.csv is `23242`, but in values.csv it's `20134`.

**Comment by danabrey** [comment]
Kenny Gainwell has a similar fate.

**Comment by tanho63** [comment]
Blast! I did mean for age to be included. Also grah on those funny ones, I’ll check the joins

-
Tan Ho
________________________________

**Comment by tanho63** [comment]
Joins here. Looks like FP switches over their post-draft IDs, so it should be reflected in tomorrow's FP values build 
![image](https://user-images.githubusercontent.com/38083823/117974859-0a586500-b2fc-11eb-9fe1-c8682300a7ba.png)

**Comment by tanho63** [comment]
Also thank goodness for sportsdata_ids because switching between Kenny and Kenneth Gainwell would have driven me bananas

**Comment by tanho63** [comment]
Age should be fixed now!

**Comment by danabrey** [comment]
Awesome, thanks!

**Comment by tanho63** [comment]
Looks like sync went well! (Checked my own dynastyassistant scores 😂) 

I'll close this off for now, please feel free to open new issues as necessary!

**Comment by danabrey** [comment]
Really appreciate it, thanks!

Yep, we're getting rookies syncing fine now, lots of happy people.
