### ISSUE TITLE
[Data Request] Missing Tony Jones Jr.

### ISSUE THREAD

**Issue by jsokol** [dynastyprocess/data#27]
Love your trade calculator for use with my Dynasty league.  I was looking at a trade involving the new Saints #2 RB, Tony Jones Jr., and couldn't find him in the system.  Is that an oversight or am I doing something wrong?  Thanks!

**Comment by tanho63** [comment]
Hiya! Not exactly an oversight - https://www.fantasypros.com/nfl/rankings/dynasty-rb.php doesn't have a ranking for Tony Jones yet so there's no value number. I don't personally add/adjust any rankings so it's a bit more waiting for FP to adjust

**Comment by jsokol** [comment]
Ah, that's one of the other sites I use for rankings and had noticed he wasn't there, either.  Thanks for the quick response and explanation!  And for the awesome tool!
