### ISSUE TITLE
Rotoworld uses three types of IDs 

### ISSUE THREAD

**Issue by tomweingarten** [dynastyprocess/data#6]
Thanks for creating this database, it's very helpful. I've only looked into this a little, but it looks like Rotoworld uses different IDs for the player's page URL, the API calls to get news about the player, and the player's profile image. The ID listed in this database appears to be the profile image ID. It would be helpful to have all three, depending on what the user's goal is. If you're going to choose only one, I might recommend the player URL ID, because you can get the other two from there.

For example, for Aaron Rodgers the URL is: https://www.rotoworld.com/football/nfl/player/7815/aaron-rodgers
The ID for his profile image (the one used in DynastyProcess) is 3118
The ID used for searching news articles is 39071

**Comment by tanho63** [comment]
Hey Tom, thanks for reaching out! I'll have a look - our DB is primarily based as a compilation of other APIs with a dose of name-merging. MFL and Sleeper both seem to have Rodgers listed as 3118 for rotoworld ID, which I agree is a little unhelpful! 

I'll see what I can do to find a source/scrape for the right ID - may have to crawl Rotoworld which isn't super ideal.

**Comment by tomweingarten** [comment]
I may have spoken too soon! It looks like there is a way to use the IDs in your database (like 3118) to retrieve players by using this URL: http://www.rotoworld.com/player/nfl/{PLAYER_ID}

It redirects you to the canonical URL, which has a different ID. From there, you can parse the javascript to get the third ID you need for AJAX calls by looking for the 'currentPath' property in the drupal-settings-json.

Thanks for putting this together!

**Comment by tanho63** [comment]
Neat! I'll have to remember/save that in a documentation somewhere :)
